<script>
	import {
		Section,
		Container,
		Button,
		Stack,
		Tagline,
		AdaptableGrid,
		NumberBall
	} from "$lib/components/atoms/index";
	import { dappTitle } from "$lib/config/config";
import { each } from "svelte/internal";

	export let steps = [
		{
			title: "Create Collection",
			description: "Fill out basic information like a name, description, image, and price for your NFT Collection."
		},
		{
			title: "Upload Your Assets",
			description: "Upload all of your metadata and associated images for your collection using your own IPFS token. We automatically format and upload your assets while ensuring you have complete control over the storage of your assets."
		},
		{
			title: "Preview Your Collection",
			description: "Take a quick peak through your NFT Collection to make sure everything is aligned and ready for final deployment."
		},
		{
			title: "Deploy Your Contract",
			description: "Deploy your autogenerated smart contract and upload your assets to the contract itself."
		}
	]
</script>

<Section>
	<Container>
		<AdaptableGrid>
			<div class="video sticky">
				<video width="100%" height="100%" autoplay loop muted>
					<source src="emerald2.webm" type="video/webm" />
					<track kind="captions" />
					Your browser does not support the video tag.
				</video>
			</div>
			<Stack align="flex-start" justify="center">
				<Tagline>CREATE YOUR COLLECTION</Tagline>
				<h2>Create an NFT collection without code</h2>
				{#each steps as step, i}
					<div class="feature">
						<Stack direction="row" gap="0.5em" align="center" justify="flex-start">
							<NumberBall>{i + 1}</NumberBall>
							<h4>{step.title}</h4>
						</Stack>
						<p>
							{step.description}
						</p>
					</div>
				{/each}
				<div class="buttons-group">
					<Button class="medium ghost" href="/guide/en/welcome" leftIcon="document-text"
						>Guide</Button>
					<Button class="medium" href="/collection-generator" leftIcon="add-circle"
						>Generate Collection</Button>
				</div>
			</Stack>
		</AdaptableGrid>
	</Container>
</Section>

<style type="scss">
	@use "../../../styles/abstracts" as *;

	.sticky {
		@include mq(medium) {
			position: sticky;
			top: 4rem;
			height: fit-content;
		}
	}

	h2 {
		margin-bottom: 2rem;
	}

	.feature {
		h4 {
			font-size: var(--fs-400);
		}
		p {
			font-size: var(--fs-300);
			margin-top: 1em;
			margin-bottom: 2em;
		}
	}

	.buttons-group {
		display: flex;
		flex-direction: column;
		gap: 2rem;

		@include mq(small) {
			flex-direction: row;
		}
	}
</style>
