<script>
	import {
		Section,
		Container,
		Button,
		Stack,
		Tagline,
		AdaptableGrid,
	} from "$lib/components/atoms/index";
	import { dappTitle } from "$lib/config/config";
</script>

<Section>
	<Container>
		<AdaptableGrid>
			<div class="video sticky">
				<video width="100%" height="100%" autoplay loop muted>
					<source src="emerald2.webm" type="video/webm" />
					<track kind="captions" />
					Your browser does not support the video tag.
				</video>
			</div>

			<Stack align="flex-start" justify="center">
				<Tagline>CREATE YOUR COLLECTION</Tagline>
				<h2>Create an NFT collection without code</h2>
				<div class="feature">
					<h4>1. Create a Collection</h4>
					<p>
						Fill out basic information like a name, description, image, and
						price for your NFT Collection.
					</p>
				</div>
				<div class="feature">
					<h4>2. Upload Your Assets</h4>
					<p>
						Upload all of your metadata and associated images for your
						collection using your own IPFS token. We automatically format and
						upload your assets while ensuring you have complete control over the
						storage of your assets.
					</p>
				</div>
				<div class="feature">
					<h4>3. Preview Your Collection</h4>
					<p>
						Take a quick peak through your NFT Collection to make sure
						everything is aligned and ready for final deployment.
					</p>
				</div>
				<div class="feature">
					<h4>4. Deploy Your Contract</h4>
					<p>
						Deploy your autogenerated smart contract and upload your assets to
						the contract itself.
					</p>
				</div>
				<div class="buttons-group">
					<Button class="medium ghost" href="/guide/en/welcome" leftIcon="document-text"
						>Guide</Button>
					<Button class="medium" href="/collection-generator" leftIcon="add-circle"
						>Generate Collection</Button>
				</div>
			</Stack>
		</AdaptableGrid>
	</Container>
</Section>

<style type="scss">
	@use "../../../styles/abstracts" as *;

	.sticky {
		@include mq(medium) {
			position: sticky;
			top: 4rem;
			height: fit-content;
		}
	}

	h2 {
		margin-bottom: 2rem;
	}

	.feature {
		h4 {
			font-size: var(--fs-400);
			margin-bottom: 0.5em;
		}
		p {
			font-size: var(--fs-300);
			margin-bottom: 2em;
		}
	}

	.buttons-group {
		display: flex;
		flex-direction: row;
		gap: 2rem;
	}
</style>
