<script>
	import {
		Section,
		Container,
		Button,
		Stack,
		Tagline,
		AdaptableGrid,
		Ball,
		Feature,
	} from "$atoms";

	let steps = [
		{
			title: "Create Collection",
			description:
				"Fill out basic information like a name, description, image, and price for your NFT Collection.",
		},
		{
			title: "Upload & Preview",
			description:
				"Upload all of your metadata and associated images for your collection using your own IPFS token. We automatically format and upload your assets while ensuring you have complete control over the storage of your assets.",
		},
		{
			title: "Deploy Your Contract",
			description:
				"Deploy your autogenerated smart contract and upload your assets to the contract itself. A marketplace will automatically set up for you.",
		},
	];
</script>

<div class="background">
	<Section>
		<Container class="width-large">
			<AdaptableGrid>
				<div class="video sticky">
					<video width="100%" height="100%" autoplay loop muted>
						<source src="emerald2.webm" type="video/webm" />
						<source src="emerald2.mp4" type="video/mp4" />
						<track kind="captions" />
						Your browser does not support the video tag.
					</video>
				</div>
				<Stack align="flex-start" justify="center">
					<Tagline>HOW IT WORKS</Tagline>
					<h2>Create, Upload, Launch</h2>
					{#each steps as step, i}
						<Feature title={step.title} description={step.description}>
							<Ball accent={true} size="2.4rem">{i + 1}</Ball>
						</Feature>
					{/each}
					<div class="buttons-group">
						<Button
							class="medium ghost"
							href="/guide/en/welcome"
							leftIcon="document-text">Guide</Button>
						<Button
							class="medium"
							href="/contract-generator"
							leftIcon="add-circle">Generate Collection</Button>
					</div>
				</Stack>
			</AdaptableGrid>
		</Container>
	</Section>
</div>

<style type="scss">
	@use "../../../styles/abstracts" as *;

	.sticky {
		@include mq(medium) {
			position: sticky;
			top: 16vh;
			height: fit-content;
		}
	}

	h2 {
		margin-bottom: 2rem;
	}

	.buttons-group {
		display: flex;
		flex-direction: column;
		gap: 2rem;

		@include mq(small) {
			flex-direction: row;
		}
	}

	.background {
		background: radial-gradient(
			ellipse at bottom,
			var(--clr-primary-soft-t9),
			transparent
		);
		backdrop-filter: blur(10px);
	}

	video {
		border-radius: 3rem;
	}
</style>
