<script>
	import {
		Section,
		Container,
		Stack,
		AdaptableGrid,
	} from "$lib/components/atoms/index";
</script>

<Section>
	<Container>
		<Stack align="center" gap="4rem">
			<h2>Create Your NFT Collection in Minutes</h2>
			<!-- TODO: ADD GENERATOR PREVIEW -->
			<AdaptableGrid minWidth="20rem">
				<div class="feature">
					<h4>1. Create a Collection</h4>
					<p>
						Fill out basic information like a name, description, image, and
						price for your NFT Collection.
					</p>
				</div>
				<div class="feature">
					<h4>2. Upload Your Assets</h4>
					<p>
						Upload all of your metadata and associated images for your
						collection using your own IPFS token. We automatically format and
						upload your assets while ensuring you have complete control over the
						storage of your assets.
					</p>
				</div>
				<div class="feature">
					<h4>3. Preview Your Collection</h4>
					<p>
						Take a quick peak through your NFT Collection to make sure
						everything is aligned and ready for final deployment.
					</p>
				</div>
				<div class="feature">
					<h4>4. Deploy Your Contract</h4>
					<p>
						Deploy your autogenerated smart contract and upload your assets to
						the contract itself.
					</p>
				</div>
			</AdaptableGrid>
		</Stack>
	</Container>
</Section>

<style type="scss">
	h2 {
		text-align: center;
	}

	.feature {
		text-align: left;

		h4 {
			font-size: var(--fs-400);
			margin-bottom: 0.5em;
		}

		p {
			font-size: var(--fs-300);
		}
	}
</style>
